name: Web status
on:
  push:
  schedule:
  - cron: '*/5 * * * *'
  issues:
     types: [opened]
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: build
      uses: minoplhy/ups2@v1.3.5-i
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_KEY }}
      with:
        site: "https://kylz.nl"
        site2: "https://crappy.kylz.nl"
        site3: "https://m21.kylz.nl"
        source_file: '/index.html'
        destination_repo: 'minoplhy/alive-test'
        destination_folder: 'docs'
        user_email: 'what@m21.kylz.nl'
        user_name: 'Builder'
        commit_message: 'Updated status'
    - name: Checkout
      uses: actions/checkout@v2

