name: Push File
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: build
      uses: minoplhy/ups2@1.3.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_KEY }}
      with:
        site: "kylz.nl"
        source_file: '/index.html'
        destination_repo: 'minoplhy/alive-test'
        destination_folder: 'html'
        user_email: 'what@m21.kylz.nl'
        user_name: 'Builder'
        commit_message: 'Updated status'
    - name: Checkout
      uses: actions/checkout@v2

