name: Push File

on: push

jobs:


  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: build
      uses: minoplhy/ups2@v.1.2
      with:
        site: "kylz.nl"
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'index.html'
        destination_repo: 'minoplhy/alive-test'
        destination_folder: 'html'
        user_email: 'what@m21.kylz.nl'
        user_name: 'minoplhy'
        commit_message: 'Test'
